
/**
 *
 * @author Jenna Rigby
 */
public class HelpScreen extends javax.swing.JFrame {
   private static String username; //Static so it is available in all classes
   private int i;
    /**
     * Creates new form HelpScreen
     */
    public HelpScreen(String username) {
        initComponents();
        this.username = username;
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHelpScreen = new javax.swing.JPanel();
        btnRules = new javax.swing.JButton();
        btnFAQs = new javax.swing.JButton();
        btnContact = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaHelp = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        lblHelpTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHelpScreen.setBackground(new java.awt.Color(0, 0, 0));
        pnlHelpScreen.setPreferredSize(new java.awt.Dimension(760, 450));

        btnRules.setBackground(new java.awt.Color(255, 255, 0));
        btnRules.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnRules.setText("RULES");
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });

        btnFAQs.setBackground(new java.awt.Color(0, 0, 204));
        btnFAQs.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnFAQs.setText("FAQs");
        btnFAQs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAQsActionPerformed(evt);
            }
        });

        btnContact.setBackground(new java.awt.Color(255, 0, 0));
        btnContact.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnContact.setText("CONTACT");
        btnContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactActionPerformed(evt);
            }
        });

        txaHelp.setEditable(false);
        txaHelp.setBackground(new java.awt.Color(0, 0, 0));
        txaHelp.setColumns(20);
        txaHelp.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txaHelp.setForeground(new java.awt.Color(255, 255, 255));
        txaHelp.setRows(5);
        jScrollPane1.setViewportView(txaHelp);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackIcon.JPG"))); // NOI18N
        btnBack.setToolTipText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHelpTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblHelpTitle.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblHelpTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHelpTitle.setText("HELP");

        javax.swing.GroupLayout pnlHelpScreenLayout = new javax.swing.GroupLayout(pnlHelpScreen);
        pnlHelpScreen.setLayout(pnlHelpScreenLayout);
        pnlHelpScreenLayout.setHorizontalGroup(
            pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                        .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnRules))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHelpScreenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnFAQs)
                                .addGap(8, 8, 8)
                                .addComponent(btnContact))
                            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(lblHelpTitle)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlHelpScreenLayout.setVerticalGroup(
            pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHelpTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRules)
                    .addComponent(btnFAQs, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContact, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHelpScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHelpScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactActionPerformed
        Help help = new Help();
        txaHelp.setText(help.getContact());
        txaHelp.setCaretPosition(0);
    }//GEN-LAST:event_btnContactActionPerformed

    private void btnFAQsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAQsActionPerformed
        Help help = new Help();
        txaHelp.setText(help.getFaqs());
        txaHelp.setCaretPosition(0);
    }//GEN-LAST:event_btnFAQsActionPerformed

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
         Help help = new Help();
         txaHelp.setText(help.getRules());
         txaHelp.setCaretPosition(0);

    }//GEN-LAST:event_btnRulesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
          this.dispose();      
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpScreen

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpScreen

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpScreen

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpScreen

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpScreen(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContact;
    private javax.swing.JButton btnFAQs;
    private javax.swing.JButton btnRules;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHelpTitle;
    private javax.swing.JPanel pnlHelpScreen;
    private javax.swing.JTextArea txaHelp;
    // End of variables declaration//GEN-END:variables
}
