
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jenna Rigby
 */
public class SearchedProfileScreen extends javax.swing.JFrame {

    private static String searchedUser;
    private static String username;

    /**
     * Creates new form SearchedUserProfileScreen
     *
     * @param searchedUser
     */
    private DBConnection db = new DBConnection();

    public SearchedProfileScreen(String searchedUser, String username) {
        try {
            this.searchedUser = searchedUser;
            this.username = username;
            initComponents();
            this.setResizable(false);

            Users users = new Users(db);
            Boolean exists = false;
            for (int i = 0; i < users.getArraySize(); i++) {
                if (users.getUser(i).getUsername().equalsIgnoreCase
                 (searchedUser)) {
                    exists = true;
                    break;
                } else {
                    exists = false;
                }

            }
            if (exists) {
                txfUsername.setText(searchedUser);
                Profile profile = new Profile(searchedUser);
                txfRank.setText(profile.getRank() + "");
                txfLevel.setText(profile.getLevel());
                txfScore.setText("" + profile.getScore());

                //Display friends
                Friends allFriends = new Friends(db);
                DefaultListModel listFriends = new DefaultListModel();
                allFriends.populateFriendArray();
                for (int i = 0; i < allFriends.getArraySize(); i++) {
                    if (allFriends.getFriend(i).getUsername().equalsIgnoreCase
                     (searchedUser)) {
                        listFriends.addElement(allFriends.getFriend(i)
                                .getFriend());
                        lstUserFriends.setModel(listFriends);
                    }
                }

                //Display songs
                Songs allSongs = new Songs(db);
                DefaultListModel listSongs = new DefaultListModel();
                allSongs.populateSongArray();
                for (int i = 0; i < allSongs.getArraySize(); i++) {
                    if (allSongs.getSong(i).getUsername().equalsIgnoreCase
                       (searchedUser)) {
                        listSongs.addElement(allSongs.getSong(i).getSongName());
                        lstUserCreations.setModel(listSongs);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "User does not "
                        + "exist", "", HEIGHT);

            }

        } catch (SQLException ex) {
            System.out.println("Error when connecting to database.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        txfLevel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txfRank = new javax.swing.JTextField();
        txfScore = new javax.swing.JTextField();
        lblCreations = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUserCreations = new javax.swing.JList<>();
        lblFriends = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUserFriends = new javax.swing.JList<>();
        btnAddFriend = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackIcon.JPG"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 33, 33));

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HelpIcon.JPG"))); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 31, 33));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("USER'S PROFILE");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 11, 414, -1));

        txfUsername.setEditable(false);
        txfUsername.setBackground(new java.awt.Color(0, 0, 0));
        txfUsername.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txfUsername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 96, 140, 30));

        txfLevel.setEditable(false);
        txfLevel.setBackground(new java.awt.Color(0, 0, 0));
        txfLevel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txfLevel.setForeground(new java.awt.Color(255, 255, 255));
        txfLevel.setToolTipText("LEVEL");
        jPanel1.add(txfLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 159, 720, 7));

        txfRank.setEditable(false);
        txfRank.setBackground(new java.awt.Color(0, 0, 0));
        txfRank.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txfRank.setForeground(new java.awt.Color(255, 255, 255));
        txfRank.setToolTipText("RANK");
        jPanel1.add(txfRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 101, 70, -1));

        txfScore.setEditable(false);
        txfScore.setBackground(new java.awt.Color(0, 0, 0));
        txfScore.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txfScore.setForeground(new java.awt.Color(255, 255, 255));
        txfScore.setToolTipText("SCORE");
        jPanel1.add(txfScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 132, 70, -1));

        lblCreations.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCreations.setForeground(new java.awt.Color(255, 255, 255));
        lblCreations.setText("CREATIONS");
        jPanel1.add(lblCreations, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 177, -1, 26));

        lstUserCreations.setBackground(new java.awt.Color(0, 0, 0));
        lstUserCreations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lstUserCreations.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lstUserCreations.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lstUserCreations);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 214, 225, 226));

        lblFriends.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFriends.setForeground(new java.awt.Color(255, 255, 255));
        lblFriends.setText("FRIENDS");
        jPanel1.add(lblFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 181, 62, -1));

        lstUserFriends.setBackground(new java.awt.Color(0, 0, 0));
        lstUserFriends.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        lstUserFriends.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lstUserFriends.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(lstUserFriends);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 214, 225, 226));

        btnAddFriend.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFriend.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAddFriend.setText("ADD FRIEND");
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 214, 153, -1));

        lblScore.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("SCORE");
        jPanel1.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 50, 20));

        lblLevel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel.setText("LEVEL");
        jPanel1.add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        HelpScreen helpScreen = new HelpScreen(username);
        helpScreen.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        LeaderboardScreen leaderboard = new LeaderboardScreen(username);
        leaderboard.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        try {
            DBConnection db = new DBConnection();
            boolean notFriends = true;
            Friends friends = new Friends(db);
            for (int i = 0; i < friends.getArraySize(); i++) {
                if (friends.getFriend(i).getUsername().equalsIgnoreCase
                (username) && friends.getFriend(i).getFriend().equalsIgnoreCase
                 (searchedUser)) {
                    JOptionPane.showMessageDialog(rootPane, "You are already "
                            + "friends with this user.", "", HEIGHT);
                    notFriends = false;
                    break;
                } else {
                    if (txfUsername.getText().isBlank()) {
                        JOptionPane.showMessageDialog(rootPane, "User does not "
                                + "exist.", "", HEIGHT);
                        break;
                    }
                }
            }
            if (notFriends) {
                db.addFriend(username, searchedUser);
            }

        } catch (SQLException ex) {
            System.out.println("Error connecting to database.");
        }
    }//GEN-LAST:event_btnAddFriendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchedProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchedProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchedProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchedProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchedProfileScreen(searchedUser, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCreations;
    private javax.swing.JLabel lblFriends;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstUserCreations;
    private javax.swing.JList<String> lstUserFriends;
    private javax.swing.JTextField txfLevel;
    private javax.swing.JTextField txfRank;
    private javax.swing.JTextField txfScore;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
