
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jenna Rigby
 */
public class UserProfileScreen extends javax.swing.JFrame {

    private static String username;

    /**
     * Creates new form UserProfileScreen
     * @param username
     */
  
    public UserProfileScreen(String username) {
        this.username = username;
        initComponents();
        this.setResizable(false);

        try {
            txfUsername.setText(username);
            Profile profile = new Profile(username);
            txfRank.setText(profile.getRank() + "");
            txfLevel.setText(profile.getLevel());
            txfScore.setText("" + profile.getScore());

            //Displays user's friends in list
            DBConnection db = new DBConnection();
            Friends allFriends = new Friends(db);
            DefaultListModel listFriends = new DefaultListModel();
            allFriends.populateFriendArray();
            for (int i = 0; i < allFriends.getArraySize(); i++) {
                if (allFriends.getFriend(i).getUsername().equalsIgnoreCase
                 (username)) {
                    listFriends.addElement(allFriends.getFriend(i).getFriend());
                    lstFriends.setModel(listFriends);
                }
            }

            //Displays songs
            Songs allSongs = new Songs(db);
            DefaultListModel listSongs = new DefaultListModel();
            allSongs.populateSongArray();
            for (int i = 0; i < allSongs.getArraySize(); i++) {
                if (allSongs.getSong(i).getUsername().equalsIgnoreCase
                   (username)) {
                    listSongs.addElement(allSongs.getSong(i).getSongName());
                    lstCreations.setModel(listSongs);
                }
            }

            //Display uploads
            Uploads allUploads = new Uploads(db);
            DefaultListModel listUploads = new DefaultListModel();
            allUploads.populateUploadsArray();
            for (int i = 0; i < allUploads.getArraySize(); i++) {
                if (allUploads.getUpload(i).getUsername().equalsIgnoreCase
                    (username)) {
                    listUploads.addElement(allUploads.getUpload(i).getSoundName
                     ());
                    lstUploads.setModel(listUploads);

                }

            }

        } catch (SQLException ex) {
            System.out.println("Error connecting to database");
        }
    }


    /*  public void sendUsername(String username){
        profile = new Profile(username);
        
        this.username = username;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProfileScreen = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txfUsername = new javax.swing.JTextField();
        txfLevel = new javax.swing.JTextField();
        txfRank = new javax.swing.JTextField();
        txfScore = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCreations = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUploads = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFriends = new javax.swing.JList<>();
        lblCreations = new javax.swing.JLabel();
        lblUploads = new javax.swing.JLabel();
        lblFriends = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        txfCreationName = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlProfileScreen.setBackground(new java.awt.Color(0, 0, 0));

        lblProfile.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblProfile.setText("PROFILE");

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeIcon.JPG"))); // NOI18N
        btnHome.setToolTipText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        txfUsername.setEditable(false);
        txfUsername.setBackground(new java.awt.Color(0, 0, 0));
        txfUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txfUsername.setForeground(new java.awt.Color(255, 255, 255));
        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });

        txfLevel.setEditable(false);
        txfLevel.setBackground(new java.awt.Color(0, 0, 0));
        txfLevel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txfLevel.setForeground(new java.awt.Color(255, 255, 255));
        txfLevel.setToolTipText("LEVEL");

        txfRank.setEditable(false);
        txfRank.setBackground(new java.awt.Color(0, 0, 0));
        txfRank.setForeground(new java.awt.Color(255, 255, 255));
        txfRank.setToolTipText("RANK");

        txfScore.setEditable(false);
        txfScore.setBackground(new java.awt.Color(0, 0, 0));
        txfScore.setForeground(new java.awt.Color(255, 255, 255));
        txfScore.setToolTipText("SCORE");

        lstCreations.setBackground(new java.awt.Color(0, 0, 0));
        lstCreations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lstCreations.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lstCreations.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lstCreations);

        lstUploads.setBackground(new java.awt.Color(0, 0, 0));
        lstUploads.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        lstUploads.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lstUploads.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(lstUploads);

        lstFriends.setBackground(new java.awt.Color(0, 0, 0));
        lstFriends.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        lstFriends.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lstFriends.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(lstFriends);

        lblCreations.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCreations.setForeground(new java.awt.Color(255, 255, 255));
        lblCreations.setText("CREATIONS");

        lblUploads.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUploads.setForeground(new java.awt.Color(255, 255, 255));
        lblUploads.setText("UPLOADS");

        lblFriends.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFriends.setForeground(new java.awt.Color(255, 255, 255));
        lblFriends.setText("FRIENDS");

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HelpIcon.JPG"))); // NOI18N
        btnHelp.setToolTipText("HELP");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("SCORE");

        lblLevel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel.setText("LEVEL");

        txfCreationName.setText("search...");
        txfCreationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCreationNameActionPerformed(evt);
            }
        });

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProfileScreenLayout = new javax.swing.GroupLayout(pnlProfileScreen);
        pnlProfileScreen.setLayout(pnlProfileScreenLayout);
        pnlProfileScreenLayout.setHorizontalGroup(
            pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addComponent(lblProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txfCreationName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                                        .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(442, 442, 442)
                                .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfRank, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(txfScore))))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblCreations)
                .addGap(175, 175, 175)
                .addComponent(lblUploads, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFriends)
                .addGap(122, 122, 122))
        );
        pnlProfileScreenLayout.setVerticalGroup(
            pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfile)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                        .addComponent(txfRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                        .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreations, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUploads)
                    .addComponent(lblFriends))
                .addGap(13, 13, 13)
                .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlProfileScreenLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlProfileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfCreationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlay))
                        .addGap(10, 10, 10)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProfileScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProfileScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        HelpScreen helpScreen = new HelpScreen(username);
        helpScreen.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        HomeScreen home = new HomeScreen(username);
        home.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed

    }//GEN-LAST:event_txfUsernameActionPerformed

    private void txfCreationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCreationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCreationNameActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if (txfCreationName.getText().isBlank()) {
            
        }else{
            try {
                DBConnection db = new DBConnection();
                Songs songs = new Songs(db); 
                Users users = new Users(db);               
                songs.populateSongArray();
                
                //Finds the song using the songName and username, reads it using
                //a scanner and plays each audio by calling the Create class,
                //pausing the thread to make sure each audio plays on time
                for (int i = 0; i < songs.getArraySize(); i++) {
                    if (songs.getSong(i).getUsername().equals(username) && 
                    songs.getSong(i).getSongName().equals(txfCreationName.
                            getText())) {
                        String song = songs.getSong(i).getSong();
                        Scanner scLine = new Scanner(song).useDelimiter("#");
                        while (scLine.hasNext()) {
                        String audioClip = scLine.next() + ".wav";
                        int milliseconds = scLine.nextInt();
                        System.out.println(audioClip + " " + milliseconds);
                        Create create = new Create();
                        Thread.sleep(milliseconds);
                        create.playAudio(audioClip);
                        }
                    }
                }
                        
                  
            
            } catch (SQLException ex) {
                System.out.println("Error connecting to database.");
            } catch (InterruptedException ex) {
                System.out.println("Error pausing thread.");
            }
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfileScreen(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPlay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCreations;
    private javax.swing.JLabel lblFriends;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblUploads;
    private javax.swing.JList<String> lstCreations;
    private javax.swing.JList<String> lstFriends;
    private javax.swing.JList<String> lstUploads;
    private javax.swing.JPanel pnlProfileScreen;
    private javax.swing.JTextField txfCreationName;
    private javax.swing.JTextField txfLevel;
    private javax.swing.JTextField txfRank;
    private javax.swing.JTextField txfScore;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
